### ISSUE TITLE
swagger support

### ISSUE THREAD

**Issue by arschles** [quii/mockingjay-server#11]
it would be really nice to pass MJ a [swagger](http://swagger.io/) schema, along with some of the flakiness parameters and have MJ serve the endpoints in the schema according to the specified flakiness.

**Comment by quii** [comment]
If Swagger's schema is stable now that could be a good idea, especially if people are defining APIs using it a lot.

Given Swagger is a documentation thing though why would you want to have that for fakes? 

Might see how feasible it is, or of course if you want to try then do a PR.

**Comment by arschles** [comment]
yea, swagger 2.0 is stable. Swagger core is mostly for docs, but it's a standardized definition language and there are a lot of code generation tools for it. the idea here would be that MJ ingests the definition and serves each endpoint. might be able to get a PR going for this

**Comment by quii** [comment]
It would be great if you did! If I find time I might do it myself because we use swagger a lot where i work anyway.

**Comment by arschles** [comment]
cool. not sure timeline, etc... but I'll try!
