### ISSUE TITLE
Compatibility check doesn't verify HTTP response headers

### ISSUE THREAD

**Issue by rtolar** [quii/mockingjay-server#16]
The wiki at https://github.com/quii/mockingjay-server/wiki/How-does-compatibility-work%3F 
says: 
"Mockingjay will check easy things such as status codes, URLs and headers to see if they match. If you define you want a particular header and it isn't in the response, then it will fail."

However, it's not checking HTTP response headers.

Set up two mocking servers - one to be the 'real' server, and one to be the 'mock'.
Both are identical, except that we expect a response header of "content-type: application/json".
So, we specify the expectation in the mock server config, and omit it from the real server config.

========================================
hello-mock.txt:
---
 - name: My very important integration point
   request:
     uri: /hello
     method: POST
     body: "Chris" # * matches any body
   response:
     code: 200
     body: '{"message": "hello, Chris"}'   # * matches any body
     headers:
       content-type: application/json
=========================================
hello-real.txt:
---
 - name: My very important integration point
   request:
     uri: /hello
     method: POST
     body: "Chris" # * matches any body
   response:
     code: 200
     body: '{"message": "hello, Chris"}'   # * matches any body

========================================

And then run the 'real' server via:
windows_amd64_mockingjay-server.exe -config=./hello-real.txt -port 9091

Run the mock server via:

C:\dev\2015\mockingjay>windows_amd64_mockingjay-server.exe -config=./hello-mock.txt -port 9090 -realURL=http://localhost:9091
2015/06/09 23:10:27 ? My very important integration point (POST /hello)
2015/06/09 23:10:27 All endpoints are compatible

The server reports that all endpoints are compatible, even though the 'real' server did not provide a content-type header.

Expected result:  report an incompatibilty

Output from the 'real' server - showing that it is not returning a Content-Type header:
C:\dev\2015\mockingjay> curl -H "Content- Type: application/json" -X POST -d "Chris" -i http://localhost:9091/hello
HTTP/1.1 200 OK
Date: Wed, 10 Jun 2015 05:21:45 GMT
Content-Length: 27
Content-Type: text/plain; charset=utf-8

{"message": "hello, Chris"}

Output from the 'mock' server - showing the Content-Type header is returned:
C:\dev\2015\mockingjay> curl -H "Content- Type: application/json" -X POST -d "Chris" -i http://localhost:9090/hello
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 10 Jun 2015 05:24:36 GMT
Content-Length: 27

{"message": "hello, Chris"}

**Comment by quii** [comment]
Quite funny really, now that I look at the code it's not even really a bug, I just haven't done it! I have included some example files, I'll see if I can fix it today.

Thanks for reporting.

**Comment by quii** [comment]
I have pushed a commit which hopefully fixes this (forgot to put hashtag in commit, darn).

https://github.com/quii/mockingjay-server/commit/71497c94c7ebfa9e6f7110ec7dd73ce300e73e55

The output given the configurations in examples/issue16 produce this:

````
2015/06/10 07:33:57 ✗ Endpoint with response headers (GET /hello) is incompatible with http://localhost:9090 Some headers were missing from the downstream server [content-type]
2015/06/10 07:33:57 At least one endpoint was incompatible with the real URL supplied
````

I will close this issue for now but if you have any problems please let me know - and thanks again
