### ISSUE TITLE
Wildcard on request URL

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#17]
Useful if you want to just return a canned response regardless of the URL

**Comment by shulhi** [comment]
+1 on this feature. It would be great to have wildcard/pattern (regex maybe?) matching on the URI.

e.g. `/jobs/jobsid-*/status` will match `/jobs/jobsid-1232/status`.

By any chance, are you working on this right now?

**Comment by quii** [comment]
I'm not, probably wont be able to for at least a week. Feel free to have a crack yourself though :)

**Comment by quii** [comment]
On reflection I cant see how this can work very well with the CDC element of mockingjay; what URL can MJ send to the real server to test against?

So Im going to close this for now unless I can think of something elegant
