### ISSUE TITLE
Writing log messages to stderr

### ISSUE THREAD

**Issue by lightswitch05** [quii/mockingjay-server#18]
I'm not familiar with the go language, but it appears `log.Printf` prints to `stderr` instead of the expected `stdout` for info-level log messages. I created a gulp task to start my mock api server when I startup my dev server:

```javascript
    gulp.task('serve:api', [], function () {
      var serverPath = './linux_amd64_mockingjay-server';
      var mockPath = path.join(__dirname, './mock.yml');
      var mockingjay = spawn(serverPath, ['-config=./mock.yml']);
    
      mockingjay.stdout.on('data', function (data) {
        gutil.log('stdout: ' + data);
      });
    
      mockingjay.stderr.on('data', function (data) {
        gutil.log(gutil.colors.red('[Mockingjay Error]: ' + data));
      });
    
      mockingjay.on('close', function (code) {
        gutil.log('Mockingjay exited with code ' + code);
      });
    });
```

when running I get the message `Serving 2 endpoints defined from ./mock.yml on port 9090` through `stderr`:

![image](https://cloud.githubusercontent.com/assets/598803/8547526/85bef712-248d-11e5-9b9d-f281fb8cc07f.png)

**Comment by quii** [comment]
Ah yes, my bad. It's easy enough to fix, will try and get that sorted in the next day or 2 when i have some spare time.

Thanks for reporting.

**Comment by quii** [comment]
@lightswitch05 I dont have much experience with gulp, but this console output seems to prove that it's fixed, hopefully. 

````
Chriss-MacBook-Air:mockingjay-server qui$ mockingjay-server -config=examples/example.yaml 1> stdout
^CChriss-MacBook-Air:mockingjay-server qui$ cat stdout 
mocking-jay: 2015/07/07 17:22:55 Serving 3 endpoints defined from examples/example.yaml on port 9090
````

Could you give it a go?

**Comment by lightswitch05** [comment]
@quii I'm having trouble getting it to build - I've just been using the release binary. I've never used go before. I think your test above is sufficient, if it comes back up in a later release I can reopen it.

**Comment by quii** [comment]
If it's a release binary you shouldn't have to build it, just copy the binary to your path, or whatever. Could you describe what you're doing in more detail?

**Comment by quii** [comment]
Just so it's clear, I've made a new release to fix this bug so you should just download the new version and copy it over the one you had before, and then it should work with Gulp

**Comment by lightswitch05** [comment]
Sorry, I didn't release you made a new release. I just re-tested and it works great. Thank you!

![image](https://cloud.githubusercontent.com/assets/598803/8557932/b8413d4e-24ce-11e5-85a8-09f61e472846.png)

**Comment by quii** [comment]
Woot. I appreciate the feedback on the bug, do feel free to let me know of anything else that sucks :)
