### ISSUE TITLE
Possible leaked fd

### ISSUE THREAD

**Issue by sethgrid** [quii/mockingjay-server#19]
you have:
https://github.com/quii/mockingjay-server/blob/master/compatability.go#L79

If an unexpected response code comes in, you return prior to closing the response body. Easy fix: just move that line up to before the if-status-code check

cheers

**Comment by sethgrid** [comment]
Just made a PR for it.
Also, something to consider which could be important in some edge cases (esp when testing/proxying): there is a flaw in the standard lib's handling of errors and redirects whereby you could have a situation where a response body exists and an error! The go team is aware of the issue and intend to keep the current functionality to not break backwards compatibility (in fact, they patched it at one point and someone complained). See https://github.com/golang/go/blob/master/src/net/http/client.go#L427

**Comment by quii** [comment]
Thanks, I will check this out this evening, not on a proper computer right now. Do the tests pass?
