### ISSUE TITLE
Better error message for empty array in example JSON

### ISSUE THREAD

**Issue by boocockp** [quii/mockingjay-server#2]
When mockingjay-server is being used to run CDC tests, and the body element of the config contains JSON data which has an empty array, there is an exception thrown by a Go panic. It would be good if there was a clean error message to the user. It would be even better if the message pointed out exactly which element of the JSON was wrong.

**Comment by quii** [comment]
Fixed by fixing this bug in jsonequaliser (https://github.com/quii/jsonequaliser/commit/179dd7ae202c85157e61e9188d803bab04aab5d1)
