### ISSUE TITLE
Make a nice web UI to view the configuration

### ISSUE THREAD

**Issue by quii** [quii/mockingjay-server#23]
~~Currently if you hit an unknown endpoint you get a text based, boring and hard to read representation of your YAML.~~

It would be better if MJ had a nice UI to view the endpoints, be able to try the tests out and even run the CDC part in the browser. 

Eventually this could lead to MJ configuration being totally editable via a UI instead of editing a YAML file, which might make it a bit more accessible.

**Comment by kirillDanshin** [comment]
+1

**Comment by quii** [comment]
This is now done! `/mj-admin`

Or at least, a pretty decent version. It will need iterating over but specific issues can be raised as they come up
