### ISSUE TITLE
For the go-uninititated, could you provide a little more installation info please?

### ISSUE THREAD

**Issue by mikebrules** [quii/mockingjay-server#24]
Using "go get ...." might have worked (maybe), but I have no $mockingjay-server application available on my terminal after sourcing all various profiles etc. Please can you update with any other steps required. I'm on MAC OS X. Thanks

**Comment by quii** [comment]
Hi

Sorry to hear you're having problems. I probably need to signpost this wiki page a little clearer

https://github.com/quii/mockingjay-server/wiki/Installing

tl;dr You can download a binary, stick it somewhere on your path and you're good to go.

**Comment by quii** [comment]
If `go get` "worked", then the binary would've appeared inside $GOPATH/bin. 

It is common for gophers to add $GOPATH/bin to their $PATH so that those applications are available.

**Comment by mikebrules** [comment]
@quii thanks very much. It was me being a GO newbie - I found the binary shortly after posting. Think it could be useful to mention it installs in GOPATH in case anyone else stumbles across it. Thanks for getting back

**Comment by quii** [comment]
@mikebrules No problem, and I have updated the wiki. Thanks for the feedback :)
