### ISSUE TITLE
Running contract tests against the Producer

### ISSUE THREAD

**Issue by alonpeer** [quii/mockingjay-server#38]
I understand how I can use this to mock the producer, and run tests on the consumer. 
But what about the other way around - running tests on the producer against the same contracts and making sure the producer does break them?

**Comment by quii** [comment]
This is more of an organisational challenge to do with consumer driven contracts in general. How do you make a producer run your CDCs? 

If you dont have "access" to the API (i.e third party) there's not a lot you can do, you cant force them! 

However, if it's in the same organisation/team, you can certainly do *something*. In my previous role we had a fairly sophisticated system based on conventions where a given project could "declare" what services it depended on in a configuration file and what test to run. Our build systems would then pull these tests to where it's required for the automated builds. 

I would start with something simple though, find a way to distribute the test to them in perhaps an ad-hoc way and then evolve it to suit your various build pipelines. 

Does that help?

**Comment by quii** [comment]
Just noticed this

> running tests on the producer against the same contracts

If it's not clear you do

`mockingjay-server -config=your.yaml -realURL=http://some-api.com`

**Comment by alonpeer** [comment]
Oh I missed that! 
So I can run my producer's server locally and then run `mockingjay-server -config=your.yaml -realURL=http://localhost:5000` to verify the tests, correct?

So assuming I'm able to resolve the issue of sharing contract YAML files between the consumer and producer, I can automate running this on both ends.

Sounds right?

**Comment by quii** [comment]
Yup that's exactly it :) 

In fact, the way the acceptance tests work for this project is it runs the fake server and then runs the CDC against itself, which proves it's compatible with itself! 

Without trying to sound mean, did you read the README in full? The reason I ask is I want the readme to be as clear as possible. If you have any suggestions to make it more obvious do let me know.

Good luck and let me know if you have any other issues.

**Comment by quii** [comment]
````bash
MML242:~ chrisj$ mockingjay-server -config=/Users/chrisj/go/src/github.com/quii/mockingjay-server/examples/example.yaml &
[1] 19204
MML242:~ chrisj$ mocking-jay: 2016/04/05 12:32:05 Serving 4 endpoints defined from /Users/chrisj/go/src/github.com/quii/mockingjay-server/examples/example.yaml on port 9090

MML242:~ chrisj$ mockingjay-server -config=/Users/chrisj/go/src/github.com/quii/mockingjay-server/examples/example.yaml -realURL=http://localhost:9090
mocking-jay: 2016/04/05 12:32:28 ! IGNORED Endpoint not used for CDC
mocking-jay: 2016/04/05 12:32:28 ✓ Test endpoint (GET /hello) is compatible with http://localhost:9090
mocking-jay: 2016/04/05 12:32:28 ✓ Failing endpoint (POST /card) is compatible with http://localhost:9090
mocking-jay: 2016/04/05 12:32:28 ✓ Test endpoint 2 (DELETE /world) is compatible with http://localhost:9090
mocking-jay: 2016/04/05 12:32:28 All endpoints are compatible
````

**Comment by alonpeer** [comment]
I guess I was thrown off by the "real server" reference.
Using a real server isn't such a good practice IMO, since you want to be able to run POST, PUT and DELETE commands as well without altering production data. 
So running the server locally with a set of dockers for external resources, then running the acceptance tests against that would be a better practice.
I think the README should reference this more common practice, as explained in other frameworks such as PACTO: http://thoughtworks.github.io/pacto/patterns/cdc/
