### ISSUE TITLE
[feature-request] Ability to specify wildcards for config in CDC mode

### ISSUE THREAD

**Issue by aceakash** [quii/mockingjay-server#40]
```
mockingjay-server -config=*.yaml -realURL=http://my.awesomeservice.com
```

Wouldn't it be nice to be able to run this? 😄 

A pattern I see my team using more and more often, is to have a single yaml config file per consumer, and run them all against the same instance of our service. 
Right now, we use run mockingjay once per config (in a loop), but wildcard support would be great.

**Comment by quii** [comment]
Fixed in https://github.com/quii/mockingjay-server/releases/tag/1.9.0
