### ISSUE TITLE
go get throws assetFS undefined

### ISSUE THREAD

**Issue by thewhitetulip** [quii/mockingjay-server#50]
../../quii/mockingjay-server/main.go:45: undefined: assetFS

**Comment by quii** [comment]
Hey thanks for raising, I only haven't noticed this because I've always used the docker image to run it. Maybe that can be an alternative for you until I figure out how to make the go generated stuff work with go get

**Comment by quii** [comment]
@thewhitetulip I *think* i have fixed it. I deleted all the references to MJ i have on my machine that im aware of, did `go-get` and it worked, but would love if you could check it on yours

**Comment by thewhitetulip** [comment]
👍 This is fixed now. Thank you :-)
